# Generated by Django 5.1.2 on 2024-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astropic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
