# Generated by Django 5.1.2 on 2024-10-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astropic', '0002_photo_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
        migrations.CreateModel(
            name='PhotoOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='astropic.photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoOfTheMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='astropic.photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoOfTheYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='astropic.photo')),
            ],
        ),
    ]
