# Generated by Django 5.1.2 on 2024-10-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astropic', '0003_remove_photo_likes_photooftheday_photoofthemonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
