# Generated by Django 5.1.2 on 2024-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astropic', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
